name: Create BigQuery DataSet in ${{ values.project_id | capitalize }}

on:
  push:
    branches: main
{% raw %}
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}

jobs:
  deploy-cloudrun:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    
    # checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    - name: configure gcp credentials
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
    - name: Validate GCP service account
      run: gcloud auth list
    # Initialize Terraform 
    - name: Terraform Init
      run: terraform init
      working-directory: .  # Where should this command be run?
      
    # Format Terraform code
    - name: Terraform Format
      run: terraform fmt
      working-directory: .
      
    # Validate the Terraform code 
    - name: Terraform Validate
      run: terraform validate
      working-directory: .
      
    # Apply the Terraform plan
    - name: terraform apply
      run: terraform apply -auto-approve
      working-directory: .
{% endraw %}  
