apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.dataset_name | dump }}
  annotations:
    backstage.io/project: ${{ values.project_id | dump }}
    backstage.io/source-location: url:https://github.com/monkmantra/gcp-bigquery-dataset-template
    github.com/project-slug: monkmantra/gcp-bigquery-dataset-template
    backstage.io/techdocs-ref: dir:.
  description: GCP BigQuery DataSet managed by Terraform
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
